### ISSUE TITLE
I have seen ur Reverse a number code, N it has Error'

### ISSUE THREAD

**Issue by anishhh238** [anishhh20/C-codes-#7]
I have seen ur Reverse a Number C++ Program, 
N as I've seen U have Error's in Ur program ....
Error'
1. after u printing " Enter an integer: "
u take ' remainder ' as input number instead of this take ' n ' as input

2. at last, printing " Reversed Number = ", print ' reversed_number ' var value

**Comment by anishhh20** [comment]
Good, to see ur Issue

**Comment by anishhh238** [comment]
Yaah, Plz assign me So, I can Fix this issue @anishhh20

**Comment by anishhh20** [comment]
Okay, sure

**Comment by anishhh238** [comment]
Thank uh, for assigning

**Comment by anishhh20** [comment]
Thank uh, for detect the issue n resolve the program
